### ISSUE TITLE
global map access in-consistency

### ISSUE THREAD

**Issue by ChinaXing** [bpftrace/bpftrace#1860]
### What reproduces the bug?

I found bpftrace can't keep consistency access of global map;

in the following code, first uprobe expected called before second one, because the first function probed calling the second function probed;

however, the condition in second probe matched, which indicate the key in golbal map @trans_end can't been saw, after first probe has 
set up;

as a evidence the first probe already executed, the map @t_e with tid as key can be accessed in second probe;
```
// end trans
uprobe:/home/yunxing.cyx/ob1.obs0/bin/observer:0x00000000035f9df0
{
  $trx_hash = (uint64)*(arg2+0xe0);
  @trans_end[$trx_hash] = nsecs;
  @trans_end_tid[$trx_hash] = tid;
  @t_e[tid] = $trx_hash;
}
// part commit
uprobe:/home/yunxing.cyx/ob1.obs0/bin/observer:0x00000000074e6420
{
  $trx_hash = (uint64)*(arg0+0x68);
  @part_commit[$trx_hash] = nsecs;
  @part_commit_tid[$trx_hash] = tid;
  if (@trans_end[$trx_hash] == 0) {
    printf("%lu, %lu, %lu, %s\n", $trx_hash, @t_e[tid], @trans_end_tid[$trx_hash], ustack());
  }
}
```
the backtrace can evidence the call relationship:

```
4798012705792818314, 4798012705792818314, 0, 
       oc::part::commit(unsigned long, bool)+0
       oc::trans::end_trans(bool, oc::TransDesc&)+542
        oc::PartService::end_trans(bool, oc::TransDesc&)+112
```
here the first probe on function : `oc::trans::end_trans`
and the second probe on function : `oc::part::commit`

### bpftrace --info

#bpftrace --info
Kernel helpers
  get_current_cgroup_id: yes
  send_signal: no
  override_return: no

Kernel features
  Loop support: no

#bpftrace --version
bpftrace v0.9.4

#uname -r
4.19.91-007.ali4000.alios7.x86_64

**Comment by amscanne** [comment]
It is years later, and probably no longer relevant but -- did you see the first probe at all? Even if it was attached at the right point (i.e. the addresses are all correct), you don't have any guarantee that you won't see the second probe first. The probes don't attach simultaneously/atomically, so you could attach probe2 and have an event first before probe1 is attached. Even if they *did* attach simultaneously/atomically that would still be true, because you could attach at the instruction before `commit` calls `end_trans` (but after the probe would have fired). So in general, I think you just need to handle that case.

Maybe this is another good argument for #1157. I'm not sure it would solve *every* case like this, but at least the window would be reduced to the second "you happened to be in the function already" case rather than the time to attach.

I hope that's helpful, and I'm happy to expand further. But given the bug was missed and is likely stale, I'd suggest that @jordalgo close it out (and I'm sure it can be reopened if there is something else or more details).
