### ISSUE TITLE
Support symbolizing enum values

### ISSUE THREAD

**Issue by danobi** [bpftrace/bpftrace#2772]
### Is your feature request related to a problem? Please describe.

Consider:
```
$ sudo bpftrace -e 'tracepoint:skb:kfree_skb { print(args->reason) }'
Attaching 1 probe...
50
50
```

bpftrace knows the type of `args->reason`:
```
$ sudo bpftrace -lv tracepoint:skb:kfree_skb
tracepoint:skb:kfree_skb
    void * skbaddr
    void * location
    unsigned short protocol
    enum skb_drop_reason reason
```

as well as the names of the values:
```
 $ sudo bpftrace -lv 'enum skb_drop_reason' | grep 50
        SKB_DROP_REASON_UNHANDLED_PROTO = 50,
```

Would be nice if bpftrace could be printing "SKB_DROP_REASON_UNHANDLED_PROTO" instead of integer values.

### Describe the solution you'd like

Ideally we just do it and tell users who want the integer values to cast the enum to an int. But that might not be backwards compatible.

### Describe alternative solutions or features you've considered

 Could reuse `str()` but overload on identifiers. That's kinda ugly though IMO. Could create a new helper. Also prefer to avoid that. Wonder how many people are depending on enums being printed as an integer. Seems like it's just an annoyance for everyone.
Maybe we can have an environ variable to control this? Not sure.

**Comment by danobi** [comment]
@ajor sounds like you've either volunteered or been volunteered :)

https://lore.kernel.org/netdev/647b0742-8806-cb66-d880-3d25fd9c3480@iogearbox.net/T/#m384a26b0b4e714f4ecb75186cac7b169882d46fb

**Comment by danobi** [comment]
Gave this some more thought. Here's what I propose as API: let printf() `%s` specifier take an enum variant.

If you try that today, it's a type error b/c printf() expects an integer. So adding this is backwards compatible. It should also be relatively intuitive, if obscure. We can fix obscurity with documentation.

Internally, whenever we know a type is an enum variant, we write the enum type name into `SizedType::name_` while keeping the actual type an integer. This is rather clean -- an integer with a name is obviously an enum.

Furthermore, I propose we allow casting from regular integer to enum types, eg. `(enum some_enum_type)123`. Such a cast does not affect generated code -- it simply causes the semantic_analyser to set SizedType::name_. This is necessary for when the kernel packs extra bits into the MSBs of enum values and masking/shifting is required. Casting an enum back to an integer simply removes SizedType::name_.

Overall (and IMHO), this is a elegant and backwards compatible way to support enum symbolization.

**Comment by ajor** [comment]
I'd also add that `$myenum` should be displayed as a string in `print($myenum)` and `@[$myenum] = $myenum`. It would be a change in behaviour, but I'd say it's more useful and few people would mind. We could add an "enum -> int" cast to let people display the integer values instead: `(int32)$myenum`.

For the implementation, why not create a new type for enums instead of reusing integers? I feel like that'd be easier to understand `type == enum` than `type == int && !name.empty()`.

**Comment by danobi** [comment]
> I'd also add that `$myenum` should be displayed as a string in `print($myenum)` and `@[$myenum] = $myenum`. It would be a change in behaviour, but I'd say it's more useful and few people would mind. We could add an "enum -> int" cast to let people display the integer values instead: `(int32)$myenum`.

Yeah, this is still on the table and I would be open to considering it. My main concern is not that people would mind (I doubt anyone would), but that machines are parsing output and might start misbehaving if we start changing contracts at runtime. Maybe it's an overblown concern, but I've made plenty of backwards incompatible changes in the past that have really blown up in my face.

> 
> For the implementation, why not create a new type for enums instead of reusing integers? I feel like that'd be easier to understand `type == enum` than `type == int && !name.empty()`.

Because fundamentally an enum is an integer. Adding another primitive type is always an option, but it's an expensive choice to make. If you wanted to add a `Type::enum`, you'd have to update all these occurrences to take enum as well, right?

```
$ rg -e "Type::integer|IsIntegerTy" | wc -l
117
```
It'd be an ongoing consideration for lots of new codepaths and features in the future. Rather than it being localized.

And `type == int && !name.empty()` could always be done as:
```
bool IsEnumTy() { return type_ == Type::integer && !name_ .empty() }
```

**Comment by ajor** [comment]
> > I'd also add that `$myenum` should be displayed as a string in `print($myenum)` and `@[$myenum] = $myenum`. It would be a change in behaviour, but I'd say it's more useful and few people would mind. We could add an "enum -> int" cast to let people display the integer values instead: `(int32)$myenum`.
> 
> Yeah, this is still on the table and I would be open to considering it. My main concern is not that people would mind (I doubt anyone would), but that machines are parsing output and might start misbehaving if we start changing contracts at runtime. Maybe it's an overblown concern, but I've made plenty of backwards incompatible changes in the past that have really blown up in my face.

The original requested use-case for enum symbolication was `@[args->reason] = count();`, so we'll need to support this in some form to satisfy people.

One way we could maintain backwards compatibility is by continuing to parse enum types from BTF as integers. Then users would need an explicit cast to an enum to actually have it print as one: `@[(enum skb_drop_reason)args->reason] = count();`.

I'm not sure if it's worth the added steps in order to preserve backwards compatibility here though, as it makes enums harder to work with. It'd add friction for anyone writing new scripts (who'd probably want enum names) in order to preserve legacy behaviour for unknown users.

> Because fundamentally an enum is an integer. Adding another primitive type is always an option, but it's an expensive choice to make. If you wanted to add a `Type::enum`, you'd have to update all these occurrences to take enum as well, right?
> 
> ```
> $ rg -e "Type::integer|IsIntegerTy" | wc -l
> 117
> ```

In memory an int and an enum are the same, but semantically they're different types. `enum + enum` doesn't make sense, for example.

**Comment by danobi** [comment]
> > Because fundamentally an enum is an integer. Adding another primitive type is always an option, but it's an expensive choice to make. If you wanted to add a `Type::enum`, you'd have to update all these occurrences to take enum as well, right?
> > ```
> > $ rg -e "Type::integer|IsIntegerTy" | wc -l
> > 117
> > ```
> 
> In memory an int and an enum are the same, but semantically they're different types. `enum + enum` doesn't make sense, for example.

Hmm, no I think that's still valid. Here's an example of enum + int in kernel: https://github.com/torvalds/linux/blob/55027e689933ba2e64f3d245fb1ff185b3e7fc81/kernel/bpf/verifier.c#L8521

And also according to C standard: https://en.cppreference.com/w/c/language/enum:
> Enumerated types are integer types, and as such can be used anywhere other integer types can, including in [implicit conversions](https://en.cppreference.com/w/c/language/conversion) and [arithmetic operators](https://en.cppreference.com/w/c/language/operator_arithmetic).

**Comment by jordalgo** [comment]
Do we know of any use cases in C, or, more specifically BPF C code, of using enums in arithmetic operations? Also if we make enum it's own type that doesn't prevent us from allowing arithmetic operations on enums later as long as each enum has a backing int right?

**Comment by danobi** [comment]
I think deciding whether or not to make enums behave differently than integers is a separate and much bigger discussion. For one, I am fairly skeptical the costs outweigh the benefits. The cost is some pretty gnarly complexity in lots of the core paths of the project. And it's unclear to me what the benefits are. And then there's backwards compat. Breaking backwards compat without good reason is a dangerous game. We won't feel the pain or consequences for at least a year or so. Most of the danger is social -- people won't feel comfortable investing time in the tool if all their old stuff keeps breaking.

**Comment by ajor** [comment]
It seems that there are two issues here that can be separated:
1. Backwards compatibility
2. Enum type semantics

**Backwards compatibility**
Since we don't have any concept on an "enum" in BpfScript right now, we can easily introduce a new "enum" type with whatever semantics we like, without breaking backwards compatibility. The only requirement for compatibility is that we continue to parse enums (from source, DWARF or BTF) as integers. Then require users explicitly cast their data into an enum, e.g. `(enum skb_drop_reason)args->reason`.

I do think there's value in breaking compatibility and parsing enums as enums, but want to be clear that this is a separate issue from the semantics.

(Reason for wanting to break compatibility is so that in the original use-case it is simple to symbolicate enums: `@[args->reason]`)

**Semantics**
> What we have today is in-line with both C and C++ which is probably 90%+ of what our userbase is familiar with. And I've not seen nor had any issues with implicit enum conversions in the past.

Not quite true - the C++ designers felt enums were something that could be improved over C and created "enum class" with different semantics. The reasons [are listed here](https://www.stroustrup.com/C++11FAQ.html#enum), of which the first is applicable to this discussion:
> conventional enums implicitly convert to int, causing errors when someone does not want an enumeration to act as an integer.

I think we should be prioritising creating a better language over ease of implementation. Since we haven't got any enum type yet, why not use enums with the semantics that most modern languages have decided were safer?

**Comment by ajor** [comment]
Also, it seems likely that at some point we'll want to let users define and use their own enums in BpfScript, so we'll need to take that into account too.
