### ISSUE TITLE
Replace get_stackid

### ISSUE THREAD

**Issue by jordalgo** [bpftrace/bpftrace#2962]
bpf_get_stackid() is broken by design. 

First, stacks can suffer from hash collisions and we can lose stacks. We receive collision errors in userspace b/c we do not set BPF_F_REUSE_STACKID. Note that we should **NEVER** set this flag b/c then we can silently receive unrelated stacks in userspace.

Second, there is not a great way to reduce the frequency of collision (other than increasing map size) b/c multiple probes can be sharing the same stack (remember they are hashed). As a result, we cannot delete entries in this map b/c we don't know when all the sharers are gone.

Fortunately, we haven't seen many bug reports about missing stacks (or maybe people don't notice or care). 

Some possible solutions:

1. Create a map (probably BPF_MAP_TYPE_HASH) where the key is the stack (uint64_t stack[MAX_STACK_DEPTH]) and the value is an id (uint32_t). Then call bpf_get_stack() and have a custom function insert into this map and generate a new id or return the id if the stack already exists. e.g.
```
static uint32_t get_stack_id(void* map, struct stack_t* stack) {
    uint32_t* id = bpf_map_lookup_elem(map, stack);
    if (id) {
      return *id;
    } else {
      uint32_t new_id = __sync_fetch_and_add(&next_stack_id, 1);
      int error = bpf_map_update_elem(map, stack, &new_id, BPF_NOEXIST);
      if (!error) {
        return new_id;
      }
      if (error == -EEXIST) {
        // Another thread updated the map already with the same stack.
        // It should exist now.
        id = bpf_map_lookup_elem(map, stack);
        if (!id) {
          // This shouldn't happen.
          return 0;
        }
        return *id;
      }
      return 0;
    }
  }
```

Then in userspace, iterate over the map and flip it so we can do stack lookups.

2. Use bpf_get_stack() to get the actual stack trace and pass it to userspace through the ring buffer.  However, there is additional complexity with this b/c we need to set up a percpu map to use as scratch space for bpf_get_stack() to write into. But using the stack directly might not work well b/c it would take too much stack space.

**Comment by danobi** [comment]
>  However, there is additional complexity with this b/c we need to set up a percpu map to use as scratch space for bpf_get_stack() to write into

I think we have `createGetScratchMap()` in irbuilderbpf as generic infra for this. Should at least the scratch space part is not too difficult

**Comment by javierhonduco** [comment]
@jordalgo This is a problem I've seen in the wild and that as you mention there's not a great fix for it. It's great that this is being discussed. Some thoughts:

> where the key is the stack (uint64_t stack[MAX_STACK_DEPTH]) 

Unfortunately this won't work for kernels older than 5.11, has then there was a limit of 512 bytes for `BPF_MAP_TYPE_HASH` keys. More details [here](https://github.com/parca-dev/parca-agent/pull/996). 

What I have done in the past is using `bpf_get_stackid()` to write to scratch space, [get a 64 bit hash of the stack](https://github.com/parca-dev/parca-agent/blob/3d326734de7129682dd95d798683247142445742/bpf/unwinders/hash.h) in bpf, and use a map where we keep the hash as key and the value is the stack itself. This doesn't fix all the problems you mentioned but doubling the size of the hash type can help with collisions.

Another advantage of using `bpf_get_stackid()` is that with the return value we can calculate how many frames might (*) have been successfully unwound, so we can have some simple heuristics to detect unwind errors, if desired. For example, fewer than 2 frames is considered an error, as most likely we'll always unwind `main` and `_start`.

(*): Might, as the kernel will only stop unwinding on errors reading memory, there could be some garbage frames.

**Comment by jordalgo** [comment]
@javierhonduco Good to hear from you! Thanks for the info about the kernel restriction on key size. I can look into some conditional logic based on the kernel version (although that might be messy) but in the meantime, using a 64bit hash, as you pointed out, at least reduces hash collisions. Maybe we can use the pid or comm as an additional key though that's bound to lead to some duplicated stacks...

> What I have done in the past is using bpf_get_stackid() to write to scratch space

I'm not sure I understand this part. Why do you use `bpf_get_stackid` if you're creating the hashes yourself and keeping track of your own map?

**Comment by OlivierLi** [comment]
Hello,

I just want to thank you for working on this and confirm that someone has noticed even if no-one came forward until now.

I work on Chromium and I've gotten empty stacks with "failed to look up stack id -17".

It's worying to me when looking at the data because the volume of empty stacks is non-negligeable and I don't know if I have to care about what was dropped.

**Comment by jordalgo** [comment]
There is still some additional work we could do around this but closing for now with this PR: https://github.com/bpftrace/bpftrace/pull/3060

**Comment by aktau** [comment]
I haven't seen this issue while using bpftrace. However I found this issue when I was trying to figure out what was wrong with `bpf_get_stackid()`, as was hinted in https://youtu.be/ImOOLwGyj-w?t=562 by @tanelpoder. I'm not sure what Tanel means when he says "no need for large stack maps in kernel mem" as my first thought was that IDs are smaller (if vulnerable to collisions). Likely they mean to just stream out full stacks to userspace... Anyway, just thought I'd leave a cookie.

**Comment by tanelpoder** [comment]
The `bpf_get_stackid()` is a convenient feature and it works OK enough for short-running ad-hoc eBPF scripts. But for long running, general, always-on instrumentation you hit the hash collision problem (your scripts potentially report wrong stacks on collision, etc). One option to alleviate, but not fix, this issue is to just make the BPF_STACK hashmap bigger, so that there's a lower chance of collision. But that means more kernel memory usage as the stack map uses stack_ids as the key, but the stack return pointers have to be stored in the hashtable as the payload too. 127 x 8B return pointer per stack means 1 kB per bucket. So a hashtable with 131072 buckets will take 128 MB of kernel memory (and for stack maps I think you can't lazily allocate as you go).

And for long-enough running eBPF apps that see all kinds of stacks, you'll hit collisions sooner or later.

I switched to emitting `build_id` + `array of stack return addresses` from eBPF and symbolizing them later outside of the kernel. 

Later on I saw @anakryiko's presentation and at Meta they had came to a similar conclusion:

_All but one use cases at Meta switched to bpf_get_stack()!_

http://oldvger.kernel.org/bpfconf2024_material/Evolution_of_stack_trace_capture_with_BPF_LSF_MM_BPF_2024.pdf
