### ISSUE TITLE
uprobes with function names containing dollar sign fail

### ISSUE THREAD

**Issue by amiremohamadi** [bpftrace/bpftrace#3160]
i think bpftrace encounters **parsing** difficulties with function names containing dollar signs ($). dollar signs are commonly used in mangled function names generated by rust complier.

https://rust-lang.github.io/rfcs/2603-rust-symbol-name-mangling-v0.html

**Comment by amiremohamadi** [comment]
for instance take a look at this:

```sh
$ bpftrace -l "uprobe:/tmp/qdrant:*

uprobe:qdrant:_ZN67_$LT$regex_syntax..hir..LookSet$u20$as$u20$core..cmp..PartialEq$GT$2eq17hbf472fe7f62896eaE
uprobe:qdrant:_ZN67_$LT$reqwest..tls..TlsBackend$u20$as$u20$core..default..Default$GT$7default17hdff9fd41950b9d49E
uprobe:qdrant:_ZN67_$LT$ring..aead..block..Block$u20$as$u20$core..ops..bit..BitXor$GT$6bitxor17h43947c2b18288922E
uprobe:qdrant:_ZN67_$LT$ring..agreement..Algorithm$u20$as$u20$core..cmp..PartialEq$GT$2eq17hfa52dffa2abf9b6fE
uprobe:qdrant:_ZN67_$LT$ring..arithmetic..bigint..N0$u20$as$u20$core..clone..Clone$GT$5clone17h5e86278622600d6bE
uprobe:qdrant:_ZN67_$LT$ron..de..value..ValueVisitor$u20$as$u20$serde..de..Visitor$GT$10visit_bool17ha4f828533b571352E
uprobe:qdrant:_ZN67_$LT$ron..de..value..ValueVisitor$u20$as$u20$serde..de..Visitor$GT$10visit_char17hd7380207f2b272e8E
```

**Comment by amiremohamadi** [comment]
also demangling is not a solution here. sometimes it's not possible to do that, so IMHO we should hack the parser in a way to support $ signs.

**Comment by amiremohamadi** [comment]
i found a temporary solution for my case. if I replace all those dollar signs with asterisk symbol it works perfectcly.

**Comment by ajor** [comment]
You should be able to quote the symbol names to have them go through the parser, like this:

```
uprobe:qdrant:"_ZN67_$LT$regex_syntax..hir..LookSet$u20$as$u20$core..cmp..PartialEq$GT$2eq17hbf472fe7f62896eaE" { }
```

**Comment by ajor** [comment]
To give a more complete response to the original request about changing the parser:
1. It'd make the parser more complicated, because `uprobe:exe:$1` already has a distinct meaning - `$1` is an argument passed in from the command line.
2. We don't really want to add specific syntax to support various languages, because where do we stop? C++, Rust, Go, Java, Haskell, Zig, Nim, ...? What if some languages uses colons (`:`) in its mangled names?

That's not to say that we don't want to support these languages, only that we shouldn't incorporate their specifics into bpftrace's syntax.

A similar issue has come up as we're currently adding support for understanding C++ types - how can we parse a type name like `std::vector<int>`?

The best solution we've got currently is to escape them in some way so that the parser doesn't try to understand them. That's where the quotes come in.
