### ISSUE TITLE
Data corruption when using `printf` and/or `if` on an associative-array map

### ISSUE THREAD

**Issue by dkogan** [bpftrace/bpftrace#3194]
Hi. I'm seeing very odd behavior. Would appreciate being pointed in the right direction. System info at the bottom.

I have this sample `tst.bt`:

```
tracepoint:syscalls:sys_enter_openat
{
  $key    = str(args->filename);
  @keymap = $key;

  @t[$key] = elapsed;
}

tracepoint:syscalls:sys_exit_openat
{
  $key = @keymap;

  printf("before: %s\n", $key);

  //if(1)
  if(@t[$key])
  {
      printf("xxx %ld\n", elapsed - @t[$key]);
      //print(elapsed - @t[$key]);
  }

  printf("after: %s\n", $key);
}
```

The path is stored in `$key` and `@keymap`. And the open() timestamp is stored in `@t[$key]`.

When `open()` exits, we print the latency. Should be easy, but the code above doesn't work:

```
$ sudo /tmp/bpftrace /tmp/tst.bt | head -n 10

Attaching 2 probes...
before: /proc/stat
xxx 17300209
after:
before: /proc/net/dev
xxx 239592489
after:
before: /proc/stat
xxx 1018839740
after:
```

Note that

- `sys_exit_openat` sees the path correctly, but the `if() { printf }` block somehow breaks the value of `$key`
- The reported latencies are way too high. It doesn't take over a second to open those files.

Furthermore, two workarounds are available in the code above (by switching to the commented-out option):

- Using `if(1)` instead of the given `if(@t[$key])` fixes it
- Or we can replace the `printf()` with the `print()`

This feels like either a bug, or a very unfriendly trap. Any ideas?

I'm using a bleeding-edge build of bpftrace from git, against recent-but-not-bleeding-edge libbpf, libbpfcc. This is a mostly up-to-date Debian system on amd64:

```
$ sudo /tmp/bpftrace --info
System
  OS: Linux 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24)
  Arch: x86_64

Build
  version: v0.20.0-162-g4c8b2
  LLVM: 17.0.6
  unsafe probe: no
  bfd: yes
  liblldb (DWARF support): no
  libsystemd (systemd notify support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: no
  get_func_ip: yes
  jiffies64: yes
  for_each_map_elem: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes

$ dpkg -l | grep 'libbpf'
ii  libbpf1:amd64    1:1.3.0-2
ii  libbpfcc:amd64   0.26.0+ds-1+b1

$ uname -a
Linux fatty 5.19.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1 (2022-09-24) x86_64 GNU/Linux
```

Thanks

**Comment by ajor** [comment]
There's definitely a bug here, thanks for finding it!

There are a couple of different problems which I think we can separate.

#### Problem 1 - Overly high latencies

At first glance, I don't think this one is actually a bpftrace bug. Your script isn't handling the case where multiple `openat` system calls could be happening in parallel on different threads/CPUs.

The solution is to use `tid` as a key in every map access so that multiple threads don't stomp on each other's data:
```
tracepoint:syscalls:sys_enter_openat
{
  $key = str(args->filename);
  @keymap[tid] = $key;

  @t[tid, $key] = elapsed;
}
```

(This might also fix the second problem, but that's just down to the luck of compiler optimisations)

#### Problem 2 - variable lifetime analysis bug

The missing value for `$key` after the `if` statement is a real bpftrace bug. We're not correctly calculating the lifetime of the `$key` variable so the optimiser thinks it's dead too early and overwrites its memory.

Technical details for future reference: we're inserting two `lifetime.end` instructions for the same variable. I think this is likely the same issue as #3000. Looking at the common patterns between the two issues, it might be using variables in map-keys that is the problem.

**Comment by ajor** [comment]
Confirmed this as the same issue as #3000. I've also tested your script with the fix in #3195 and the data for `$key` looks good.

**Comment by dkogan** [comment]
This fixes both the simple reproducer in this report AND the bigger script that I was having trouble with originally. Thank you!

It sounds like #3195 is a workaround and not a fix, so I'll let yall close this bug report when you feel it's ready.

**Comment by janet-campbell** [comment]
I'm putting in mitigation for this issue now in my code, but I think it will solve a long-standing issue I've had where data would make it into some maps but not others.  This is a great find.

**Comment by ajor** [comment]
> It sounds like #3195 is a workaround and not a fix, so I'll let yall close this bug report when you feel it's ready.

I think that fix is as good as we'll be getting in the near future - it's the same approach that we were already taking elsewhere in code generation, we'd just missed this spot. Closing.
