### ISSUE TITLE
quay.io/iovisor/bpftrace is out of date

### ISSUE THREAD

**Issue by gonzoua** [bpftrace/bpftrace#3514]
Container image at quay.io/iovisor/bpftrace seems to be out of date, it's on version 0.19.0 while the current version is 0.21.2:

```
$ sudo docker run --rm -ti --privileged \
    -v /sys/kernel/debug:/sys/kernel/debug \
        quay.io/iovisor/bpftrace \
        bpftrace --version
bpftrace v0.19.0
```

**Comment by danobi** [comment]
Hi, we stopped shipping container images for bpftrace. They were mostly done as part of shipping statically linked binaries. If you're looking for those, we ship our "static binaries" as appimages now. See: https://github.com/bpftrace/bpftrace/blob/master/INSTALL.md#appimage-install

Otherwise I'd recommend using the distro supplied bpftrace version.
